#!/bin/bash

pyfile="$PYFILE"

if [ -z "$pyfile" ]; then
  echo "Error: PYFILE environment variable is not set."
  exit 1
elif [ ! -f "$pyfile" ]; then
  echo "Error: File '$pyfile' does not exist."
  exit 1
fi

python3 "$pyfile"